Makefile.legacy: fix two errors for generic build
I broke this in commit 7c748e2b:
./best.sh: line 29: +make: command not found

This has been broken since some functions moved from misc.c to jumbo.c
(commit 1f341404):
config.c:(.text+0x43c): undefined reference to `strlwr'
config.c:(.text+0x477): undefined reference to `strlwr'
config.c:(.text+0x706): undefined reference to `strlwr'
collect2: error: ld returned 1 exit status