For --regex=alpha, '.' and '?' need to be escaped
This avoids
error: syntax error, unexpected $end
Error, invalid regex expression.  John exiting now  base_word=??  Regex=
??