CI: disable -wError compiler flag for some jobs
The new compiler version can no longer produce a clean build. E.g.:
```
dynamic_fmt.c: In function 'prepare':
dynamic_fmt.c:1088:36: error: '$$F' directive output may be truncated writing 3 bytes into a region of size between 1 and 1024 [-Werror=format-truncation=]
 1088 |      snprintf(ct2, sizeof(ct2), "%s$$F%d%s", cpBuilding, i, split_fields[i]);
      |                                    ^~~
dynamic_fmt.c:1088:33: note: directive argument in the range [0, 9]
 1088 |      snprintf(ct2, sizeof(ct2), "%s$$F%d%s", cpBuilding, i, split_fields[i]);
      |                                 ^~~~~~~~~~~
dynamic_fmt.c:1088:6: note: 'snprintf' output 5 or more bytes (assuming 1028) into a destination of size 1024
 1088 |      snprintf(ct2, sizeof(ct2), "%s$$F%d%s", cpBuilding, i, split_fields[i]);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```